apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-openebs-sc-1 # defined in csi-setup.yaml
